### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by cidevant** [atom/keyboard-layout#1]
```bash
@cidevant ~/Code/JavaScript/Atom.io/atom-keymap-official [master] $ npm install keyboard-layout
npm WARN package.json grunt-atomdoc@1.0.0 No repository field.
-
> keyboard-layout@0.6.0 install /Users/cidevant/Code/JavaScript/Atom.io/atom-keymap-official/node_modules/keyboard-layout
> node-gyp rebuild

  CXX(target) Release/obj.target/keyboard-layout-observer/src/keyboard-layout-observer-mac.o
../src/keyboard-layout-observer-mac.mm:42:3: error: no matching function for call to 'uv_async_init'
  uv_async_init(loop, &async, asyncSendHandler);
  ^~~~~~~~~~~~~
/Users/cidevant/.node-gyp/0.10.28/deps/uv/include/uv.h:1192:15: note: candidate function not viable: no known conversion from 'void (uv_async_t *)' to
      'uv_async_cb' (aka 'void (*)(uv_async_t *, int)') for 3rd argument
UV_EXTERN int uv_async_init(uv_loop_t*, uv_async_t* async,
              ^
1 error generated.
make: *** [Release/obj.target/keyboard-layout-observer/src/keyboard-layout-observer-mac.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cidevant/Code/JavaScript/Atom.io/atom-keymap-official/node_modules/keyboard-layout
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "keyboard-layout"
npm ERR! node v0.10.28
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! keyboard-layout@0.6.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keyboard-layout@0.6.0 install script.
npm ERR! This is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.
```

**Comment by kevinsawicki** [comment]
The version of nan this library uses for building across multiple node versions was upgraded in https://github.com/atom/keyboard-layout/commit/c66dbf44235b8436aa6f5d8b456e9bc841dba66f which I think may have fixed this issue.

If you are still seeing this please comment and include the version of node and npm you are currently using if it is different from your last comment, thanks.
