### ISSUE TITLE
Fails to build on Windows: `error C2220: warning treated as error - no 'object' file generated`

### ISSUE THREAD

**Issue by emorikawa** [atom/keyboard-layout#11]
Windows 10
Visual Studio 2015
MSBuild 14

`error C2220: warning treated as error - no 'object' file generated`

```
PS C:\Code\N1> npm install keyboard-layout

> keyboard-layout@1.0.0 install C:\Code\N1\node_modules\keyboard-layout
> node-gyp rebuild


C:\Code\N1\node_modules\keyboard-layout>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  keyboard-layout-observer-windows.cc
..\src\keyboard-layout-observer-windows.cc(92): error C2220: warning treated as error - no 'object' file generated [C:\Code\N1\node_modules\k
eyboard-layout\build\keyboard-layout-observer.vcxproj]
..\src\keyboard-layout-observer-windows.cc(92): warning C4311: 'type cast': pointer truncation from 'HKL' to 'UINT' [C:\Code\N1\node_modules\
keyboard-layout\build\keyboard-layout-observer.vcxproj]
..\src\keyboard-layout-observer-windows.cc(92): warning C4302: 'type cast': truncation from 'HKL' to 'UINT' [C:\Code\N1\node_modules\keyboard
-layout\build\keyboard-layout-observer.vcxproj]
..\src\keyboard-layout-observer-windows.cc(111): warning C4311: 'type cast': pointer truncation from 'HKL' to 'UINT' [C:\Code\N1\node_modules
\keyboard-layout\build\keyboard-layout-observer.vcxproj]
..\src\keyboard-layout-observer-windows.cc(111): warning C4302: 'type cast': truncation from 'HKL' to 'UINT' [C:\Code\N1\node_modules\keyboar
d-layout\build\keyboard-layout-observer.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Code\N1\node_modules\keyboard-layout
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "keyboard-layout"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.8
npm ERR! code ELIFECYCLE

npm ERR! keyboard-layout@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keyboard-layout@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keyboard-layout package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keyboard-layout
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Code\N1\npm-debug.log
```

**Comment by thedaniel** [comment]
This library is specific to OSX keyboard layouts, I don't think you need to compile it on windows - or is this error coming from the atom build scripts?

**Comment by jgrosso** [comment]
Trying to build `atom-keymap` creates this error for me.

**Comment by marcholterman** [comment]
Installing atom-keymap on windows generates this C2220 error. Exactly as @emorikawa reported

**Comment by CharlieHess** [comment]
@thedaniel I've got a simpler fix for this here: https://github.com/atom/keyboard-layout/pull/14.

**Comment by thedaniel** [comment]
@CharlieHess I don't work on this project anymore, unfortunately.
